version: '3.8'

services:
  api:
    container_name: "cyprus_api"
    build:
      context: ./api
      dockerfile: ./scripts/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      MSSQL_SA_PASSWORD: $MSSQL_SA_PASSWORD
    depends_on:
      - db

  db:
    container_name: "cyprus_db"
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: $MSSQL_SA_PASSWORD
      ACCEPT_EULA: "Y"
