version: '3.8'

services:
  api:
    container_name: "cyprus_api"
    build:
      context: ./api
      dockerfile: ./scripts/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: Newer_use_it_in_prod111
      DB_SERVER: cyprus_db
    depends_on:
      - db

  db:
    container_name: "cyprus_db"
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1433"
    environment:
      MSSQL_SA_PASSWORD: Newer_use_it_in_prod111
      ACCEPT_EULA: "Y"
